"""add_cascade_delete_to_moderation_logs

Revision ID: d114323abf34
Revises: e1de6affaefe
Create Date: 2026-04-16 12:49:24.619821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd114323abf34'
down_revision: Union[str, Sequence[str], None] = 'e1de6affaefe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moderation_logs_review_id'), table_name='moderation_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_moderation_logs_review_id'), 'moderation_logs', ['review_id'], unique=False)
    # ### end Alembic commands ###
